# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\x06sample\"\x0f\n\rHelloWorldReq\" \n\rHelloWorldRes\x12\x0f\n\x07message\x18\x01 \x01(\t2\x82\x01\n\x11HelloWorldService\x12\x38\n\x08SayHello\x12\x15.sample.HelloWorldReq\x1a\x15.sample.HelloWorldRes\x12\x33\n\x03\x42ye\x12\x15.sample.HelloWorldReq\x1a\x15.sample.HelloWorldResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOWORLDREQ']._serialized_start=28
  _globals['_HELLOWORLDREQ']._serialized_end=43
  _globals['_HELLOWORLDRES']._serialized_start=45
  _globals['_HELLOWORLDRES']._serialized_end=77
  _globals['_HELLOWORLDSERVICE']._serialized_start=80
  _globals['_HELLOWORLDSERVICE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
